### PR TITLE
Handle Windows line endings when converting positions/offsets.

### LINKED ISSUE #32: Wrong locations for definitions for files with Windows line endings
In the analyzer log I see this:

```js
{
	"id": "29",
	"result": {
		"files": [
			"M:\\Apps\\Dart\\Dart-2.0.0-dev.55.0\\lib\\core\\uri.dart"
		],
		"targets": [
			{
				"kind": "METHOD",
				"fileIndex": 0,
				"offset": 26326,
				"length": 5,
				"startLine": 734,
				"startColumn": 14
			}
		],
		"regions": [
			{
				"offset": 29,
				"length": 5,
				"targets": [
					0
				]
			}
		]
	}
}
```

But in the VS log I see this:

```js
{
  "jsonrpc": "2.0",
  "result": {
    "range": {
      "end": {
        "character": 24,
        "line": 752
      },
      "start": {
        "character": 19,
        "line": 752
      }
    },
    "uri": "file:///M:/Apps/Dart/Dart-2.0.0-dev.55.0/lib/core/uri.dart"
  },
  "id": 22
}
```

Seems like the line numbers have somehow got messed up.

### PR DESCRIPTION
**Pull request by DanTup**
This fixes #32 by changing the lineLengths that are stored to include the end-of-line character(s) in the counts. Without it, you can't reliably translate the positions (it's possible a file has mixed line endings within the same file). I wasn't sure if there was a better way to do it (I saw the `splitMarker` function but it didn't seem used and wasn't totally sure whether it was doing what I needed).

This code is kinda messy for a few reasons:

1. In an attempt to avoid copy/pasting the entire set of sets, I put ternary operators in for the expected values, and it turned out kinda messy
2. In order to avoid duplicating the line-splitting logic, I added a `splitIntoLines` function in `file_cache.dart` that probably should be somewhere else.

Possibly for `1` you could dynamically get the expected values from the `file` string with a search? For example in Dart Code's tests we have things like this (which I think I stole from the analysis server tests):

```ts
ext.exports.renameProvider.prepareRename(doc, positionOf("D^anny"), null);
```

This does a search for the string `Danny` and then gets the position between the `D` and `a`. This makes it easy to modify the files without all the offsets in tests changing and needing updating.

Anyway, let me know what you think - I'm happy to make things better before you merge as required (also, it'd be good to run these tests on Travis+AppVeyor so they're run on both platforms for future checkins and for PRs :-))

### CODE REVIEW

**Comment by natebosch** [comment]
Good call on adding travis. That should be set up now if you merge in the change which adds the config.

File: lib/src/utils/file_cache.dart [hunk 1]
```diff
@@ -14,10 +14,22 @@ class FileCache {
...
+    // Don't use readAsLines() or we'll lose track of the different line endings (\r\n).
+    return splitIntoLines(new File(filePath).readAsStringSync());
   }
 
   void operator []=(String filePath, List<int> lines) {
     _activeFiles[filePath] = lines;
   }
 }
+
+// TODO: Where should this live?
```
Comment (natebosch) [inline lib/src/utils/file_cache.dart]: There is already a method `findLineLengths` in `position_convert.dart` - we should update that to use this logic.

**Review by natebosch — CHANGES_REQUESTED** [review]

File: lib/src/utils/file_cache.dart (hunk 1 above)
Comment (DanTup) [reply lib/src/utils/file_cache.dart]: This PR already updates the functions in there. This comment was about whether this function `splitIntoLines` would be better somewhere else. Previously the tests and real code were splitting the lines themselves, but since the logic isn't straight forward now I created this function for them. It doesn't feel like it should be in `file_cache.dart`?

**Comment by DanTup** [comment]
> Good call on adding travis. That should be set up now if you merge in the change which adds the config.

It's worth adding AppVeyor too; since Travis doesn't do Windows. I've rebased over master to get the Travis config.

File: lib/src/utils/file_cache.dart (hunk 1 above)
Comment (natebosch) [reply lib/src/utils/file_cache.dart]: It looks like `positionFromOffset` is updated but not `findLineLengths` on line 43 in `position_convert.dart`

Comment (DanTup) [reply lib/src/utils/file_cache.dart]: Oh whoops, I totally didn't read properly! I'll fix :-)

Comment (DanTup) [reply lib/src/utils/file_cache.dart]: I've moved the implementation into `findLineLengths` and deleted `splitIntoLines` since it was an exact dupe :)

**Comment by natebosch** [comment]
latest master should have an appveyor config that works

**Review by natebosch — APPROVED** [review]
LGTM. I think this approach for the tests is fine for now.

Thanks!
